server {
    listen 80;
    server_name 51.68.224.77;

    return 301 $scheme://vangaugan.doucycorp.fr$request_uri;
}

server {
        listen 80;
        listen [::]:80;
        server_name vangaugan.doucycorp.fr www.vangaugan.doucycorp.fr;

        location / {
            proxy_pass http://api:8080;
        }
}